language: go
go:
  - 1.7.x
before_install:
  - go get github.com/mattn/goveralls
script:
  - go test -v ./pkg/...
  - goveralls -service=travis-ci -v -package ./pkg/... -repotoken $COVERALLS_TOKEN || true
